global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'docker-host-alpha'

scrape_configs:
  - job_name: 'nodeexporter-master'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.2:9100']

  - job_name: 'cadvisor-master'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.2:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'nodeexporter-worker'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.3:9100']

  - job_name: 'cadvisor-worker'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.3:8080']